"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, Database, Link2, Plus, RefreshCw, Send } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { useShellProgress } from "@/components/layout/app-shell";
import { ContentCard } from "@/components/ui/content-card";
import { ProgressBar } from "@/components/ui/progress-bar";
import { SectionHeader } from "@/components/ui/section-header";
import { StatusBadge } from "@/components/ui/status-badge";
import type { DurableDataReviewPageViewModel } from "@/features/data-review/durable-data-review-view-model";
import type { AnalysisInvestigationRow, AnalysisProcedureRow, InvestigationDisposition, InvestigationPriority, InvestigationStatus, ProcedureStatus } from "@/features/data-review/data-review-workflow";

const inputClass = "min-h-9 w-full rounded-bs-sm border border-bs-border-strong bg-bs-surface px-2.5 text-xs text-bs-text-primary outline-none focus:border-bs-primary";
const buttonClass = "inline-flex min-h-8 items-center justify-center gap-1.5 rounded-bs-sm border border-bs-border-strong bg-bs-surface px-3 text-xs font-medium text-bs-text-secondary hover:bg-bs-page disabled:opacity-50";
const primaryClass = "inline-flex min-h-8 items-center justify-center gap-1.5 rounded-bs-sm bg-bs-primary px-3 text-xs font-medium text-white hover:bg-bs-primary-hover disabled:opacity-50";
const statuses: InvestigationStatus[] = ["open","in_progress","ready_for_review","closed"];
const dispositions: Array<InvestigationDisposition | ""> = ["","resolved","immaterial","adjustment_proposed","further_support_required"];
function label(value: string) { return value.replaceAll("_", " ").replace(/^./, (char) => char.toUpperCase()); }
function tone(value: string) { return ["complete","closed","ready"].includes(value) ? "success" as const : ["blocked","critical"].includes(value) ? "danger" as const : ["awaiting_review","changes_requested","ready_for_review","caution","high"].includes(value) ? "warning" as const : ["in_progress"].includes(value) ? "informational" as const : "neutral" as const; }

export function DurableDataReviewPage({ model }: { model: DurableDataReviewPageViewModel }) {
  const router = useRouter(); const setShellProgress = useShellProgress();
  const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [selectedId, setSelectedId] = useState(model.workflow?.investigations[0]?.id ?? "");
  const [newOpen, setNewOpen] = useState(false);
  const [newInvestigation, setNewInvestigation] = useState({ title:"", signalSummary:"", procedureId:"", priority:"medium" as InvestigationPriority });
  const selected = model.workflow?.investigations.find((item) => item.id === selectedId) ?? null;
  const [draft, setDraft] = useState<AnalysisInvestigationRow | null>(selected);
  const [evidenceId, setEvidenceId] = useState(""); const [reviewRationale, setReviewRationale] = useState("");
  useEffect(() => setDraft(selected), [selected]); useEffect(() => setShellProgress?.(model.workflowState?.completionPercent ?? 0), [model.workflowState?.completionPercent, setShellProgress]);
  async function mutate(body: Record<string, unknown>, success: string) { setPending(true); setError(null); setNotice(null); try { const response = await fetch(`/api/deals/${model.companyId}/phases/data-review`, { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Workflow update failed."); setNotice(success); router.refresh(); return payload.data; } catch (cause) { setError(cause instanceof Error ? cause.message : "Workflow update failed."); } finally { setPending(false); } }
  if (model.mode !== "persisted") { const unavailable=model.mode==="schema_unavailable"; return <><PageHeader eyebrow="Phase 3 of 6" title="Data Review & Analysis" description={unavailable?"The durable workflow migration must be applied before Phase 3 can be initialized.":"Initialize the durable Phase 3 workflow before assigning procedures or opening investigations."} status={<StatusBadge tone={unavailable?"warning":"neutral"}>{unavailable?"Schema unavailable":"Not initialized"}</StatusBadge>} progress={<ProgressBar value={0} label="Analysis workflow completion" />} /><main className="mx-auto max-w-bs-content px-4 py-8 md:px-6"><ContentCard className="mx-auto max-w-2xl"><div className="flex items-start gap-4"><span className="rounded-bs-md bg-bs-primary/10 p-3"><Database className="size-5 text-bs-primary" /></span><div className="flex-1"><h2 className="text-base font-semibold text-bs-text-primary">{unavailable?"Phase 3 workflow schema unavailable":"Initialize Phase 3"}</h2><p className="bs-body-text mt-2">{unavailable?"Apply migration 20260823190000_create_phase3_workflow.sql to the connected Supabase project. No workflow records were created and existing financial data remains unchanged.":"This creates the durable phase record and standard analytical procedures. It will not create owners, results, investigations, workpapers, or activity history beyond initialization."}</p>{error ? <p className="mt-3 text-xs text-bs-danger">{error}</p> : null}{!unavailable?<button disabled={pending} className={`${primaryClass} mt-4`} onClick={() => mutate({action:"initialize"},"Phase 3 initialized.")}><Database className="size-3.5" />{pending ? "Initializing…" : "Initialize Phase 3"}</button>:null}</div></div></ContentCard></main></>; }
  const workflow = model.workflow!; const state = model.workflowState!; const evidence = selected ? workflow.evidence.filter((item) => item.investigation_id === selected.id) : [];
  async function saveProcedure(item: AnalysisProcedureRow, patch: Record<string, unknown>) { await mutate({action:"update_procedure",id:item.id,version:item.version,...patch},`${item.title} saved.`); }
  async function saveInvestigation() { if (!draft) return; await mutate({action:"update_investigation",id:draft.id,version:draft.version,title:draft.title,procedureId:draft.procedure_id,ownerName:draft.owner_name,reviewerName:draft.reviewer_name,priority:draft.priority,status:draft.status,notes:draft.notes,conclusion:draft.conclusion,disposition:draft.disposition,materialityRationale:draft.materiality_rationale},`${draft.reference_code} saved.`); }
  return <><PageHeader eyebrow="Phase 3 of 6" title="Data Review & Analysis" description="Durable analytical procedures, investigations, evidence, and reviewer control over authoritative financial systems." status={<StatusBadge tone={tone(workflow.phase.status)}>{label(workflow.phase.status)}</StatusBadge>} progress={<div><div className="mb-1 flex justify-between"><span className="bs-label">Workflow completion</span><span className="bs-metadata">{state.completionPercent}%</span></div><ProgressBar value={state.completionPercent} label="Analysis workflow completion" /></div>} actions={<><Link href={model.links.sourceData} className={buttonClass}>Source Data<ArrowRight className="size-3" /></Link>{workflow.phase.status === "complete" ? <button disabled={pending} className={buttonClass} onClick={() => mutate({action:"reopen",version:workflow.phase.version,rationale:reviewRationale},"Phase reopened.")}><RefreshCw className="size-3" />Reopen</button> : <button disabled={pending || !state.reviewEligible} className={primaryClass} onClick={() => mutate({action:"submit",version:workflow.phase.version},"Phase submitted for review.")}><Send className="size-3" />{workflow.phase.status === "changes_requested" ? "Resubmit" : "Submit review"}</button>}</>} />
  {error ? <div role="alert" className="border-b border-bs-danger/20 bg-bs-danger/5 px-4 py-2 text-center text-xs text-bs-danger">{error}</div> : null}{notice ? <div role="status" className="border-b border-bs-success/20 bg-bs-success/5 px-4 py-2 text-center text-xs text-bs-success">{notice}</div> : null}
  <main className="mx-auto max-w-bs-content space-y-4 px-4 py-4 md:px-6">
    <div className="grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">{[["Documents",model.authoritative.documentCount],["Periods",model.authoritative.periodCount],["Canonical entries",model.authoritative.entryCount],["Mapping coverage",`${model.authoritative.mappingCoverage}%`],["Mapping exceptions",model.authoritative.mappingExceptions],["Reconciliation issues",model.authoritative.reconciliationFailures],["Open investigations",workflow.investigations.filter((item)=>item.status!=="closed").length],["Workflow completion",`${state.completionPercent}%`]].map(([name,value])=><ContentCard key={name} padding="compact"><p className="bs-label">{name}</p><p className="mt-1 text-xl font-semibold">{value}</p></ContentCard>)}</div>
    <div className="grid gap-4 lg:grid-cols-2"><ContentCard><SectionHeader title="Financial readiness" description="Derived from authoritative financial systems; not stored as workflow state." /><div className="mt-3 flex items-center gap-3"><StatusBadge tone={tone(model.financialReadiness.status)}>{model.authoritative.readinessLabel}</StatusBadge><span className="bs-metadata">{model.financialReadiness.reasons[0] ?? "No financial readiness blockers."}</span></div></ContentCard><ContentCard><SectionHeader title="Review gates" description="Eligibility is gate-driven, not percentage-driven." count={state.gateFailures.length} /><div className="mt-2 space-y-1">{state.gateFailures.map((item)=><p key={item} className="text-xs text-bs-warning">• {item}</p>)}{state.gateFailures.length===0?<p className="text-xs text-bs-success">Ready for analyst submission.</p>:null}</div></ContentCard></div>
    <ContentCard><SectionHeader title="Analysis procedures" description="Standard versioned procedure set; ownership and results are durable." count={workflow.procedures.length} /><div className="mt-3 divide-y divide-bs-border-subtle">{workflow.procedures.map((item)=><ProcedureEditor key={item.id} item={item} pending={pending} onSave={saveProcedure} />)}</div></ContentCard>
    <div className="grid min-h-[34rem] gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(26rem,0.85fr)]"><ContentCard padding="none"><div className="p-4"><SectionHeader title="Investigation queue" count={workflow.investigations.length} actions={<button className={primaryClass} onClick={()=>setNewOpen((value)=>!value)}><Plus className="size-3" />Open investigation</button>} />{newOpen?<div className="mt-4 grid gap-2 rounded-bs-md bg-bs-page p-3"><input aria-label="New investigation title" className={inputClass} placeholder="Investigation title" value={newInvestigation.title} onChange={(e)=>setNewInvestigation({...newInvestigation,title:e.target.value})}/><textarea aria-label="Source signal" className={inputClass} placeholder="Source signal" value={newInvestigation.signalSummary} onChange={(e)=>setNewInvestigation({...newInvestigation,signalSummary:e.target.value})}/><div className="grid grid-cols-2 gap-2"><select className={inputClass} value={newInvestigation.procedureId} onChange={(e)=>setNewInvestigation({...newInvestigation,procedureId:e.target.value})}><option value="">No procedure</option>{workflow.procedures.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select><select className={inputClass} value={newInvestigation.priority} onChange={(e)=>setNewInvestigation({...newInvestigation,priority:e.target.value as InvestigationPriority})}>{["low","medium","high","critical"].map((item)=><option key={item}>{label(item)}</option>)}</select></div><button disabled={pending||!newInvestigation.title||!newInvestigation.signalSummary} className={primaryClass} onClick={async()=>{const result=await mutate({action:"create_investigation",signalType:"manual",...newInvestigation},"Investigation opened.") as AnalysisInvestigationRow|undefined;if(result){setSelectedId(result.id);setNewOpen(false);}}}>Create</button></div>:null}</div><div className="divide-y divide-bs-border-subtle">{workflow.investigations.map((item)=><button key={item.id} className={`w-full p-4 text-left ${item.id===selectedId?"bg-bs-primary/5":"hover:bg-bs-page"}`} onClick={()=>setSelectedId(item.id)}><div className="flex justify-between gap-3"><div><p className="text-xs font-semibold">{item.reference_code} · {item.title}</p><p className="bs-metadata mt-1">{item.signal_summary}</p></div><div className="space-y-1 text-right"><StatusBadge tone={tone(item.priority)}>{label(item.priority)}</StatusBadge><StatusBadge tone={tone(item.status)}>{label(item.status)}</StatusBadge></div></div></button>)}{workflow.investigations.length===0?<p className="p-6 text-center text-xs text-bs-text-muted">No investigations have been opened.</p>:null}</div></ContentCard>
      <ContentCard>{draft?<div className="space-y-3"><SectionHeader title={`${draft.reference_code} · ${draft.title}`} description="Durable investigation record" /><label className="bs-label block">Title<input className={inputClass} value={draft.title} onChange={(e)=>setDraft({...draft,title:e.target.value})}/></label><div className="grid grid-cols-2 gap-2"><label className="bs-label">Owner<input className={inputClass} value={draft.owner_name??""} onChange={(e)=>setDraft({...draft,owner_name:e.target.value})}/></label><label className="bs-label">Reviewer<input className={inputClass} value={draft.reviewer_name??""} onChange={(e)=>setDraft({...draft,reviewer_name:e.target.value})}/></label><select aria-label="Related procedure" className={inputClass} value={draft.procedure_id??""} onChange={(e)=>setDraft({...draft,procedure_id:e.target.value||null})}><option value="">No procedure</option>{workflow.procedures.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select><select aria-label="Investigation priority" className={inputClass} value={draft.priority} onChange={(e)=>setDraft({...draft,priority:e.target.value as InvestigationPriority})}>{["low","medium","high","critical"].map((item)=><option key={item} value={item}>{label(item)}</option>)}</select><select aria-label="Investigation status" className={inputClass} value={draft.status} onChange={(e)=>setDraft({...draft,status:e.target.value as InvestigationStatus})}>{statuses.map((item)=><option key={item} value={item}>{label(item)}</option>)}</select><select aria-label="Investigation disposition" className={inputClass} value={draft.disposition??""} onChange={(e)=>setDraft({...draft,disposition:(e.target.value||null) as InvestigationDisposition|null})}>{dispositions.map((item)=><option key={item||"none"} value={item}>{item?label(item):"Undispositioned"}</option>)}</select></div><label className="bs-label block">Notes<textarea className={`${inputClass} min-h-20`} value={draft.notes??""} onChange={(e)=>setDraft({...draft,notes:e.target.value})}/></label><label className="bs-label block">Conclusion<textarea className={`${inputClass} min-h-20`} value={draft.conclusion??""} onChange={(e)=>setDraft({...draft,conclusion:e.target.value})}/></label>{draft.disposition==="immaterial"?<label className="bs-label block">Materiality rationale<textarea className={inputClass} value={draft.materiality_rationale??""} onChange={(e)=>setDraft({...draft,materiality_rationale:e.target.value})}/></label>:null}<button disabled={pending} className={primaryClass} onClick={saveInvestigation}>Save investigation</button>
      <div className="border-t border-bs-border-subtle pt-3"><p className="bs-label">Evidence</p>{evidence.map((item)=><div key={item.id} className="mt-2 flex justify-between rounded-bs-sm bg-bs-page p-2 text-xs"><span>{item.label_snapshot}</span><button className="text-bs-danger" onClick={()=>mutate({action:"detach_evidence",investigationId:draft.id,evidenceLinkId:item.id},"Evidence detached.")}>Remove</button></div>)}<div className="mt-2 flex gap-2"><select aria-label="Evidence document" className={inputClass} value={evidenceId} onChange={(e)=>setEvidenceId(e.target.value)}><option value="">Select document</option>{model.evidenceOptions.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select><button disabled={!evidenceId||pending} className={buttonClass} onClick={()=>mutate({action:"attach_evidence",investigationId:draft.id,evidenceType:"source_document",evidenceId,relationship:"supports"},"Evidence attached.")}><Link2 className="size-3"/>Attach</button></div></div>
      <div className="border-t border-bs-border-subtle pt-3"><div className="flex flex-wrap gap-2">{draft.disposition==="immaterial"?<><button className={buttonClass} onClick={()=>mutate({action:"approve_waiver",id:draft.id,rationale:draft.materiality_rationale},"Waiver approved.")}>Approve waiver</button><button className={buttonClass} onClick={()=>mutate({action:"revoke_waiver",id:draft.id,rationale:"Reviewer revoked waiver"},"Waiver revoked.")}>Revoke waiver</button></>:null}<button disabled={pending||!draft.conclusion||evidence.length===0||Boolean(draft.promoted_issue_id)} className={buttonClass} onClick={()=>mutate({action:"promote_investigation",id:draft.id,version:draft.version,category:"other",severity:draft.priority},"Finding created.")}>{draft.promoted_issue_id?"Finding created":"Promote to finding"}</button></div></div></div>:<p className="text-xs text-bs-text-muted">Select an investigation.</p>}</ContentCard></div>
    <ContentCard><SectionHeader title="Reviewer lifecycle" description="Submission, decisions, reopening, and comments are durable and auditable." /><div className="mt-3 flex flex-wrap items-end gap-2"><label className="bs-label min-w-72 flex-1">Rationale / review comment<textarea className={inputClass} value={reviewRationale} onChange={(e)=>setReviewRationale(e.target.value)}/></label>{workflow.phase.status==="awaiting_review"?<><button disabled={pending||!reviewRationale.trim()} className={buttonClass} onClick={()=>mutate({action:"request_changes",version:workflow.phase.version,rationale:reviewRationale},"Changes requested.")}>Request changes</button><button disabled={pending||!state.completionEligible} className={primaryClass} onClick={()=>mutate({action:"approve",version:workflow.phase.version,rationale:reviewRationale},"Phase approved.")}><CheckCircle2 className="size-3"/>Approve</button></>:null}<button disabled={pending||!reviewRationale.trim()} className={buttonClass} onClick={()=>mutate({action:"comment",comment:reviewRationale},"Comment recorded.")}>Add comment</button></div><div className="mt-4 divide-y divide-bs-border-subtle">{workflow.activity.slice(0,10).map((item)=><div key={item.id} className="py-2"><p className="text-xs font-medium">{label(item.event_type)}</p><p className="bs-metadata">{item.rationale||item.comment_text||`${item.from_state??""}${item.to_state?` → ${item.to_state}`:""}`} · {item.actor_name} · {new Date(item.created_at).toLocaleString()}</p></div>)}</div></ContentCard>
  </main></>;
}

function ProcedureEditor({ item, pending, onSave }: { item: AnalysisProcedureRow; pending: boolean; onSave: (item: AnalysisProcedureRow, patch: Record<string,unknown>)=>Promise<void> }) {
  const [draft,setDraft]=useState(item); useEffect(()=>setDraft(item),[item]);
  return <div className="grid gap-2 py-3 lg:grid-cols-[minmax(0,1fr)_9rem_9rem_9rem_9rem_7rem]"><div><p className="text-xs font-semibold">{item.title}</p><p className="bs-metadata">{label(item.workstream_key)} · {item.required?"Required":"Optional"}</p><input aria-label={`${item.title} result summary`} className={`${inputClass} mt-2`} placeholder="Result summary" value={draft.result_summary??""} onChange={(e)=>setDraft({...draft,result_summary:e.target.value})}/></div><input aria-label={`${item.title} owner`} className={inputClass} placeholder="Owner" value={draft.owner_name??""} onChange={(e)=>setDraft({...draft,owner_name:e.target.value})}/><input aria-label={`${item.title} reviewer`} className={inputClass} placeholder="Reviewer" value={draft.reviewer_name??""} onChange={(e)=>setDraft({...draft,reviewer_name:e.target.value})}/><input aria-label={`${item.title} due date`} type="date" className={inputClass} value={draft.due_date??""} onChange={(e)=>setDraft({...draft,due_date:e.target.value||null})}/><select aria-label={`${item.title} status`} className={inputClass} value={draft.status} onChange={(e)=>setDraft({...draft,status:e.target.value as ProcedureStatus})}>{["not_started","in_progress","ready_for_review","complete","blocked"].map((status)=><option key={status} value={status}>{label(status)}</option>)}</select><button disabled={pending} className={buttonClass} onClick={()=>onSave(item,{status:draft.status,ownerName:draft.owner_name,reviewerName:draft.reviewer_name,dueDate:draft.due_date,resultSummary:draft.result_summary})}>Save</button></div>;
}
