"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, FileText, Filter, Link2, MessageSquareText, Plus, Search, Send, X } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { ContentCard } from "@/components/ui/content-card";
import { ProgressBar } from "@/components/ui/progress-bar";
import { SectionHeader } from "@/components/ui/section-header";
import { StatusBadge } from "@/components/ui/status-badge";
import type { InformationRequest, InformationRequestPageViewModel, RequestPriority, RequestStatus, RequestTone } from "@/features/information-request/information-request-view-model";

const inputClass = "min-h-9 rounded-bs-sm border border-bs-border-strong bg-bs-surface px-2.5 text-xs text-bs-text-primary shadow-none outline-none focus:border-bs-primary focus:ring-2 focus:ring-bs-primary/10";
const buttonClass = "inline-flex min-h-8 items-center justify-center gap-1.5 rounded-bs-sm border border-bs-border-strong bg-bs-surface px-3 text-xs font-medium text-bs-text-secondary hover:bg-bs-page";
const primaryClass = "inline-flex min-h-8 items-center justify-center gap-1.5 rounded-bs-sm bg-bs-primary px-3 text-xs font-medium text-white hover:bg-bs-primary-hover";
const statuses: RequestStatus[] = ["Draft", "Requested", "Partially Received", "Received", "Under Review", "Follow-up Required", "Complete"];
const priorities: RequestPriority[] = ["Critical", "High", "Medium", "Low"];

function tone(status: RequestStatus): RequestTone {
  if (status === "Complete") return "success";
  if (status === "Received" || status === "Under Review") return "informational";
  if (status === "Partially Received" || status === "Follow-up Required") return "warning";
  return "neutral";
}
function priorityTone(priority: RequestPriority): RequestTone { return priority === "Critical" ? "danger" : priority === "High" ? "warning" : "neutral"; }
function isOverdue(item: InformationRequest) { return item.dueDate < "2026-08-23" && !["Received", "Under Review", "Complete"].includes(item.status); }
function displayDate(value: string) { const date = new Date(`${value}T12:00:00`); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(date); }

function Dialog({ title, description, children, onClose, onSave, saveLabel = "Save changes" }: { title: string; description: string; children: React.ReactNode; onClose: () => void; onSave: () => void; saveLabel?: string }) {
  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/45 p-4"><section role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-2xl overflow-hidden rounded-bs-lg border border-bs-border-subtle bg-bs-surface shadow-bs-overlay"><div className="flex items-start justify-between border-b border-bs-border-subtle px-5 py-4"><div><h2 className="text-base font-semibold text-bs-text-primary">{title}</h2><p className="bs-metadata mt-1">{description}</p></div><button type="button" aria-label="Close dialog" onClick={onClose}><X className="size-4 text-bs-text-muted" /></button></div><div className="max-h-[65vh] space-y-4 overflow-y-auto px-5 py-4">{children}</div><div className="flex justify-end gap-2 border-t border-bs-border-subtle bg-bs-page px-5 py-3"><button type="button" className={buttonClass} onClick={onClose}>Cancel</button><button type="button" className={primaryClass} onClick={onSave}>{saveLabel}</button></div></section></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="bs-label block space-y-1.5"><span>{label}</span>{children}</label>; }

export function InformationRequestPage({ model }: { model: InformationRequestPageViewModel }) {
  const [requests, setRequests] = useState(model.requests);
  const [selectedId, setSelectedId] = useState(model.requests[0]?.id ?? "");
  const [activity, setActivity] = useState(model.activity);
  const [editor, setEditor] = useState<"request" | "document" | "comment" | "review" | null>(null);
  const [draft, setDraft] = useState<InformationRequest>(model.requests[0]);
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("All");
  const [categoryFilter, setCategoryFilter] = useState("All");
  const [ownerFilter, setOwnerFilter] = useState("All");
  const [priorityFilter, setPriorityFilter] = useState("All");
  const [exceptionsOnly, setExceptionsOnly] = useState(false);
  const [comment, setComment] = useState("");
  const [linkedDocumentId, setLinkedDocumentId] = useState("");
  const [notice, setNotice] = useState<string | null>(null);
  const sequence = useRef(10);
  const selected = requests.find((item) => item.id === selectedId) ?? requests[0];

  const metrics = useMemo(() => ({ total: requests.length, outstanding: requests.filter((item) => !["Complete", "Received", "Under Review"].includes(item.status)).length, received: requests.filter((item) => ["Received", "Under Review", "Complete"].includes(item.status)).length, overdue: requests.filter(isOverdue).length, followUp: requests.filter((item) => item.followUp || item.status === "Follow-up Required").length, completion: requests.length ? Math.round((requests.filter((item) => ["Received", "Under Review", "Complete"].includes(item.status)).length / requests.length) * 100) : 0 }), [requests]);
  const filtered = useMemo(() => requests.filter((item) => (!query || `${item.id} ${item.title} ${item.description}`.toLowerCase().includes(query.toLowerCase())) && (statusFilter === "All" || item.status === statusFilter) && (categoryFilter === "All" || item.category === categoryFilter) && (ownerFilter === "All" || item.internalOwner === ownerFilter) && (priorityFilter === "All" || item.priority === priorityFilter) && (!exceptionsOnly || isOverdue(item) || item.followUp || item.status === "Partially Received")), [requests, query, statusFilter, categoryFilter, ownerFilter, priorityFilter, exceptionsOnly]);
  const blockers = requests.filter((item) => isOverdue(item) || item.followUp || item.status === "Follow-up Required" || (item.priority === "Critical" && !["Received", "Under Review", "Complete"].includes(item.status)));

  function log(title: string, detail: string) { sequence.current += 1; setActivity((current) => [{ id: `session-${sequence.current}`, title, detail, actor: "Preview User", timestamp: "Just now" }, ...current]); }
  function blankRequest(): InformationRequest { const next = String(requests.length + 1).padStart(3, "0"); return { id: `IR-${next}`, category: "Financials", title: "", description: "", priority: "High", internalOwner: model.owners[0], clientOwner: "Client controller", requestedDate: "2026-08-23", dueDate: "2026-08-28", status: "Draft", destination: model.destinations[0], documentIds: [], comments: [], followUp: false, lastActivity: "Just now", completionNote: "" }; }
  function openRequest(item?: InformationRequest) { setDraft(structuredClone(item ?? blankRequest())); setEditor("request"); }
  function saveRequest() { if (!draft.title.trim()) return; const exists = requests.some((item) => item.id === draft.id); setRequests((current) => exists ? current.map((item) => item.id === draft.id ? draft : item) : [draft, ...current]); setSelectedId(draft.id); log(exists ? "Request edited" : "Request created", `${draft.id} · ${draft.title}`); setNotice(`${draft.id} saved for this browser session`); setEditor(null); }
  function updateSelected(patch: Partial<InformationRequest>, eventTitle: string, detail: string) { if (!selected) return; const updated = { ...selected, ...patch, lastActivity: "Just now" }; setRequests((current) => current.map((item) => item.id === selected.id ? updated : item)); log(eventTitle, `${selected.id} · ${detail}`); setNotice(`${eventTitle} — prototype-only`); }

  return <>
    <PageHeader eyebrow="Phase 2 of 6" title="Information Request & Data Collection" description="Create the diligence request list, track client responses, and route received support into the authoritative deal library." status={<StatusBadge tone="informational">{model.phaseStatus}</StatusBadge>} progress={<div><div className="mb-1 flex justify-between"><span className="bs-label">Request readiness</span><span className="bs-metadata">{metrics.completion}%</span></div><ProgressBar value={metrics.completion} label="Request readiness" /></div>} actions={<><button type="button" className={buttonClass} onClick={() => setEditor("review")}><Send className="size-3.5" />Submit phase review</button><button type="button" className={primaryClass} onClick={() => openRequest()}><Plus className="size-3.5" />Add request</button></>} />
    <div className="border-b border-bs-info/20 bg-bs-info/5 px-4 py-2 text-center text-[11px] text-bs-info">Request workflow changes are session-only. Existing deal documents and Source Data remain authoritative.</div>
    {notice ? <div role="status" className="border-b border-bs-success/20 bg-bs-success/5 px-4 py-2 text-center text-[11px] text-bs-success">{notice}</div> : null}
    <div className="mx-auto max-w-bs-content space-y-4 px-4 py-4 md:px-6">
      <div className="grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-6">{[
        ["Total requests", metrics.total, "neutral"], ["Outstanding", metrics.outstanding, "warning"], ["Received", metrics.received, "success"], ["Overdue", metrics.overdue, "danger"], ["Follow-ups", metrics.followUp, "warning"], ["Completion", `${metrics.completion}%`, "informational"]
      ].map(([label, value, metricTone]) => <ContentCard key={String(label)} padding="compact"><p className="bs-label">{label}</p><div className="mt-1 flex items-end justify-between"><p className="text-xl font-semibold text-bs-text-primary">{value}</p><StatusBadge tone={metricTone as RequestTone} dot={false}>{label === "Overdue" && Number(value) > 0 ? "Chase" : "Current"}</StatusBadge></div></ContentCard>)}</div>

      <ContentCard padding="compact"><div className="flex flex-wrap items-end gap-2"><Field label="Search"><div className="relative"><Search className="absolute left-2.5 top-2.5 size-3.5 text-bs-text-muted" /><input aria-label="Search requests" className={`${inputClass} min-w-56 pl-8`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ID, title, or description" /></div></Field><Field label="Status"><select aria-label="Filter by status" className={inputClass} value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option>All</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Category"><select aria-label="Filter by category" className={inputClass} value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)}><option>All</option>{model.categories.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Owner"><select aria-label="Filter by owner" className={inputClass} value={ownerFilter} onChange={(event) => setOwnerFilter(event.target.value)}><option>All</option>{model.owners.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Priority"><select aria-label="Filter by priority" className={inputClass} value={priorityFilter} onChange={(event) => setPriorityFilter(event.target.value)}><option>All</option>{priorities.map((item) => <option key={item}>{item}</option>)}</select></Field><button type="button" aria-pressed={exceptionsOnly} className={`${buttonClass} ${exceptionsOnly ? "border-bs-warning bg-bs-warning/5 text-bs-warning" : ""}`} onClick={() => setExceptionsOnly((value) => !value)}><Filter className="size-3.5" />Exceptions only</button><span className="ml-auto bs-metadata">{filtered.length} shown</span></div></ContentCard>

      <div className="grid min-h-[40rem] gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(22rem,0.65fr)]">
        <ContentCard padding="none"><div className="px-4 pt-4"><SectionHeader title="Diligence request list" description="Outstanding support, response state, and accountable owner" count={filtered.length} /></div><div className="overflow-x-auto"><table className="mt-2 w-full min-w-[58rem]"><thead className="bg-bs-page"><tr className="border-y border-bs-border-subtle"><th className="bs-table-header px-3 py-2 text-left">Request</th><th className="bs-table-header px-3 text-left">Category</th><th className="bs-table-header px-3 text-left">Owner</th><th className="bs-table-header px-3 text-left">Priority</th><th className="bs-table-header px-3 text-left">Status</th><th className="bs-table-header px-3 text-right">Due</th><th className="bs-table-header px-3 text-right">Docs</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} onClick={() => setSelectedId(item.id)} className={`h-bs-table-row cursor-pointer border-b border-bs-border-subtle ${item.id === selected?.id ? "bg-bs-primary/5" : "hover:bg-bs-page"}`}><td className="px-3 py-2"><p className="text-[10px] font-semibold text-bs-primary">{item.id}</p><p className="max-w-sm truncate text-xs font-medium text-bs-text-primary">{item.title}</p>{item.followUp ? <p className="mt-0.5 text-[9px] font-medium text-bs-warning">Follow-up required</p> : null}</td><td className="bs-table-body px-3">{item.category}</td><td className="bs-table-body px-3">{item.internalOwner}</td><td className="px-3"><StatusBadge tone={priorityTone(item.priority)}>{item.priority}</StatusBadge></td><td className="px-3"><StatusBadge tone={tone(item.status)}>{item.status}</StatusBadge></td><td className={`px-3 text-right text-xs ${isOverdue(item) ? "font-semibold text-bs-danger" : "text-bs-text-secondary"}`}>{displayDate(item.dueDate)}{isOverdue(item) ? <span className="block text-[9px]">Overdue</span> : null}</td><td className="bs-numeric px-3">{item.documentIds.length}</td></tr>)}</tbody></table></div></ContentCard>

        {selected ? <aside className="space-y-4"><ContentCard><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold text-bs-primary">{selected.id} · {selected.category}</p><h2 className="mt-1 text-sm font-semibold text-bs-text-primary">{selected.title}</h2></div><button type="button" className={buttonClass} onClick={() => openRequest(selected)}>Edit</button></div><p className="bs-metadata mt-3 leading-5">{selected.description}</p><div className="mt-4 grid grid-cols-2 gap-3"><div><p className="bs-label">Internal owner</p><p className="mt-1 text-xs font-medium">{selected.internalOwner}</p></div><div><p className="bs-label">Client contact</p><p className="mt-1 text-xs font-medium">{selected.clientOwner}</p></div><div><p className="bs-label">Due date</p><p className={isOverdue(selected) ? "mt-1 text-xs font-semibold text-bs-danger" : "mt-1 text-xs font-medium"}>{displayDate(selected.dueDate)}</p></div><div><p className="bs-label">Destination</p><p className="mt-1 text-xs font-medium">{selected.destination}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><select aria-label="Change request status" className={inputClass} value={selected.status} onChange={(event) => updateSelected({ status: event.target.value as RequestStatus }, "Request status changed", `${selected.status} → ${event.target.value}`)}>{statuses.map((item) => <option key={item}>{item}</option>)}</select><button type="button" className={`${buttonClass} ${selected.followUp ? "border-bs-warning bg-bs-warning/5 text-bs-warning" : ""}`} onClick={() => updateSelected({ followUp: !selected.followUp, status: !selected.followUp ? "Follow-up Required" : selected.status }, !selected.followUp ? "Follow-up created" : "Follow-up cleared", selected.title)}><AlertTriangle className="size-3.5" />{selected.followUp ? "Clear follow-up" : "Add follow-up"}</button></div></ContentCard>

          <ContentCard><SectionHeader title="Related documents" description="References to authoritative deal-library records" count={selected.documentIds.length} actions={<button type="button" className={buttonClass} onClick={() => { setLinkedDocumentId(""); setEditor("document"); }}><Link2 className="size-3.5" />Link existing</button>} /><div className="mt-3 space-y-2">{selected.documentIds.map((id) => { const document = model.documents.find((item) => item.id === id); return document ? <div key={id} className="flex items-center gap-2 rounded-bs-sm border border-bs-border-subtle p-2.5"><FileText className="size-4 text-bs-primary" /><div className="min-w-0"><p className="truncate text-xs font-medium text-bs-text-primary">{document.name}</p><p className="text-[9px] text-bs-text-muted">Persisted source · {document.type}</p></div></div> : null; })}{selected.documentIds.length === 0 ? <p className="bs-metadata py-2">No source documents linked. The request is still awaiting support.</p> : null}</div><Link href={model.sourceDataHref} className="mt-3 inline-flex items-center gap-1 text-[10px] font-medium text-bs-primary">Open authoritative Source Data <ArrowRight className="size-3" /></Link></ContentCard>

          <ContentCard><SectionHeader title="Comments & request activity" actions={<button type="button" className={buttonClass} onClick={() => { setComment(""); setEditor("comment"); }}><MessageSquareText className="size-3.5" />Comment</button>} /><div className="mt-3 space-y-2">{selected.comments.map((item, index) => <p key={`${item}-${index}`} className="rounded-bs-sm bg-bs-page p-2.5 text-xs text-bs-text-secondary">{item}</p>)}<p className="bs-metadata">Last activity: {selected.lastActivity}</p></div></ContentCard>
        </aside> : null}
      </div>

      <ContentCard><SectionHeader title="Phase 2 activity trail" description="Request, ownership, response, document, follow-up, and review actions" count={activity.length} /><div className="mt-2 grid gap-x-6 lg:grid-cols-2">{activity.slice(0, 8).map((item) => <div key={item.id} className="border-b border-bs-border-subtle py-3"><p className="text-xs font-medium text-bs-text-primary">{item.title}</p><p className="bs-metadata mt-0.5">{item.detail}</p><p className="mt-1 text-[9px] text-bs-text-muted">{item.actor} · {item.timestamp}</p></div>)}</div></ContentCard>
    </div>

    {editor === "request" ? <Dialog title={requests.some((item) => item.id === draft.id) ? `Edit ${draft.id}` : "Create information request"} description="Define the required support, accountable owners, due date, and analyst-controlled destination." onClose={() => setEditor(null)} onSave={saveRequest}><div className="grid gap-3 sm:grid-cols-2"><Field label="Request ID"><input className={inputClass} value={draft.id} onChange={(event) => setDraft({ ...draft, id: event.target.value })} /></Field><Field label="Category / workstream"><select className={inputClass} value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })}>{model.categories.map((item) => <option key={item}>{item}</option>)}</select></Field></div><Field label="Request title"><input aria-label="Request title" className={inputClass} value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></Field><Field label="Detailed request"><textarea aria-label="Detailed request" className={`${inputClass} min-h-24`} value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></Field><div className="grid gap-3 sm:grid-cols-3"><Field label="Internal owner"><select aria-label="Internal owner" className={inputClass} value={draft.internalOwner} onChange={(event) => setDraft({ ...draft, internalOwner: event.target.value })}>{model.owners.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Priority"><select aria-label="Priority" className={inputClass} value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value as RequestPriority })}>{priorities.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Status"><select aria-label="Request status" className={inputClass} value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as RequestStatus })}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Requested date"><input className={inputClass} type="date" value={draft.requestedDate} onInput={(event) => setDraft({ ...draft, requestedDate: event.currentTarget.value })} /></Field><Field label="Due date"><input aria-label="Due date" className={inputClass} type="date" value={draft.dueDate} onInput={(event) => setDraft({ ...draft, dueDate: event.currentTarget.value })} /></Field><Field label="Client contact"><input className={inputClass} value={draft.clientOwner} onChange={(event) => setDraft({ ...draft, clientOwner: event.target.value })} /></Field></div><Field label="Destination in deal library"><select aria-label="Destination in deal library" className={inputClass} value={draft.destination} onChange={(event) => setDraft({ ...draft, destination: event.target.value })}>{model.destinations.map((item) => <option key={item}>{item}</option>)}</select></Field></Dialog> : null}

    {editor === "document" && selected ? <Dialog title="Link existing document" description="Create a session-only request association to an authoritative persisted document. The source record is not modified." onClose={() => setEditor(null)} onSave={() => { if (!linkedDocumentId || selected.documentIds.includes(linkedDocumentId)) return; const document = model.documents.find((item) => item.id === linkedDocumentId); updateSelected({ documentIds: [...selected.documentIds, linkedDocumentId], status: selected.status === "Requested" ? "Partially Received" : selected.status }, "Document linked", `${document?.name ?? linkedDocumentId} linked to ${selected.id}`); setEditor(null); }} saveLabel="Link document"><Field label="Existing authoritative document"><select aria-label="Existing authoritative document" className={inputClass} value={linkedDocumentId} onChange={(event) => setLinkedDocumentId(event.target.value)}><option value="">Select a document</option>{model.documents.filter((item) => !selected.documentIds.includes(item.id)).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><div className="rounded-bs-sm border border-bs-info/20 bg-bs-info/5 p-3 text-xs text-bs-text-secondary">The request stores only a prototype reference. Broadstone does not move, rename, delete, or re-upload the source file.</div></Dialog> : null}

    {editor === "comment" && selected ? <Dialog title={`Comment on ${selected.id}`} description="Comments are recorded in the session activity trail." onClose={() => setEditor(null)} onSave={() => { if (!comment.trim()) return; updateSelected({ comments: [...selected.comments, comment.trim()] }, "Comment added", `${selected.id} · ${comment.trim()}`); setEditor(null); }} saveLabel="Add comment"><Field label="Comment"><textarea aria-label="Comment" className={`${inputClass} min-h-28`} value={comment} onChange={(event) => setComment(event.target.value)} /></Field></Dialog> : null}

    {editor === "review" ? <Dialog title="Submit Phase 2 for reviewer decision" description="Exceptions may remain, but critical gaps must be acknowledged before analysis begins." onClose={() => setEditor(null)} onSave={() => { if (blockers.length > 0) return; log("Phase submitted for review", "Information readiness package submitted to the executive reviewer."); setNotice("Phase 2 submitted for reviewer decision — prototype-only"); setEditor(null); }} saveLabel={blockers.length ? "Resolve critical exceptions" : "Submit to reviewer"}>{blockers.length ? <div className="rounded-bs-md border border-bs-warning/20 bg-bs-warning/5 p-4"><p className="text-xs font-semibold text-bs-text-primary">{blockers.length} exceptions require disposition</p><p className="bs-metadata mt-1">Complete, receive, or document an accepted exception for each critical/overdue request.</p><div className="mt-3 space-y-2">{blockers.map((item) => <button key={item.id} type="button" className="flex w-full items-center justify-between rounded-bs-sm bg-bs-surface px-3 py-2 text-left" onClick={() => { setSelectedId(item.id); setEditor(null); }}><span className="text-xs text-bs-text-secondary">{item.id} · {item.title}</span><ArrowRight className="size-3.5 text-bs-primary" /></button>)}</div></div> : <div className="rounded-bs-md border border-bs-success/20 bg-bs-success/5 p-4"><p className="text-xs font-semibold text-bs-success">Information package is ready for reviewer decision</p><p className="bs-metadata mt-1">The reviewer can approve progression to analysis while documented non-critical exceptions remain open.</p></div>}</Dialog> : null}
  </>;
}
