export const FINDING_TYPES=["financial","operational","tax","accounting","data_quality","commercial","legal_compliance","other"]as const;
export const MATERIALITY_VALUES=["undetermined","immaterial","quantitatively_material","qualitatively_material","both"]as const;
export const REPORTING_TREATMENTS=["undetermined","internal_only","exclude","report_observation","key_finding"]as const;
export const IMPACT_DIMENSIONS=["revenue","gross_profit","ebitda","working_capital","net_debt","cash","purchase_price","enterprise_value","equity_value","tax","customer_concentration","revenue_durability","operational_risk","data_quality","accounting_policy","legal_compliance","other"]as const;
export const IMPACT_STATES=["none","known","estimated","range","unknown"]as const;
export type FindingMateriality=typeof MATERIALITY_VALUES[number];export type ReportingTreatment=typeof REPORTING_TREATMENTS[number];export type FindingReviewStatus="draft"|"ready_for_review"|"changes_requested"|"approved";export type ManagementResponseStatus="not_requested"|"requested"|"received"|"under_review"|"accepted"|"insufficient";
export type FindingProfile={issue_id:string;phase_id:string;reference_code:string;finding_type:typeof FINDING_TYPES[number];materiality:FindingMateriality;materiality_rationale:string|null;finding_narrative:string;transaction_implication:string|null;recommendation:string|null;resolution_narrative:string|null;management_response_status:ManagementResponseStatus;management_response:string|null;management_response_evaluation:string|null;reporting_treatment:ReportingTreatment;reporting_rationale:string|null;executive_summary:boolean;include_in_qoe_adjustments:boolean;transaction_consideration:boolean;approved_report_language:string|null;review_status:FindingReviewStatus;owner_name:string|null;reviewer_name:string|null;due_date:string|null;reviewed_by_name:string|null;reviewed_at:string|null;approved_version:number|null;version:number;created_at:string;updated_at:string};
export type FindingImpact={id:string;issue_id:string;dimension:typeof IMPACT_DIMENSIONS[number];impact_state:typeof IMPACT_STATES[number];currency:string|null;amount:number|null;range_low:number|null;range_high:number|null;period_id:string|null;basis:string|null;version:number};
export type FindingGateInput={title:string;severity:"low"|"medium"|"high"|"critical";operationalStatus:"open"|"in_review"|"resolved"|"waived";profile:FindingProfile;impacts:FindingImpact[];evidenceCount:number;responseWaived:boolean};
export function responseRequired(i:Pick<FindingGateInput,"severity"|"profile">){return["high","critical"].includes(i.severity)||["quantitatively_material","qualitatively_material","both"].includes(i.profile.materiality)}
export function reportable(t:ReportingTreatment){return t==="report_observation"||t==="key_finding"}
export function validateImpactShape(i:{impactState:string;amount?:number|null;rangeLow?:number|null;rangeHigh?:number|null;currency?:string|null;basis?:string|null}){if(["known","estimated"].includes(i.impactState))return Number.isFinite(i.amount)&&i.rangeLow==null&&i.rangeHigh==null&&Boolean(i.currency?.trim()&&i.basis?.trim());if(i.impactState==="range")return i.amount==null&&Number.isFinite(i.rangeLow)&&Number.isFinite(i.rangeHigh)&&i.rangeLow!<=i.rangeHigh!&&Boolean(i.currency?.trim()&&i.basis?.trim());if(["none","unknown"].includes(i.impactState))return i.amount==null&&i.rangeLow==null&&i.rangeHigh==null;return false}
export function resolveImpactUpdateId(i:{impactId?:unknown}){return typeof i.impactId==="string"&&i.impactId.trim()?i.impactId:null}
export function deriveFindingGates(i:FindingGateInput){const f:string[]=[],p=i.profile;if(!i.title.trim()||!p.finding_narrative.trim())f.push("Finding narrative is required.");if(p.materiality==="undetermined")f.push("Materiality must be determined.");if(p.materiality!=="undetermined"&&!p.materiality_rationale?.trim())f.push("Materiality rationale is required.");if(!p.owner_name)f.push("Owner is required.");if(!p.reviewer_name)f.push("Reviewer is required.");if(["quantitatively_material","qualitatively_material","both"].includes(p.materiality)&&!p.transaction_implication?.trim())f.push("Material findings require a transaction implication.");if(!i.impacts.length)f.push("At least one explicit impact assessment is required.");if(!i.evidenceCount)f.push("Evidence is required.");if(responseRequired(i)&&!i.responseWaived&&!p.management_response?.trim())f.push("Management response or reviewer waiver is required.");if(p.reporting_treatment==="undetermined")f.push("Reporting treatment is required.");if(p.reporting_treatment==="exclude"&&!p.reporting_rationale?.trim())f.push("Exclusion rationale is required.");if(reportable(p.reporting_treatment)&&!p.recommendation?.trim())f.push("Reportable findings require a recommendation.");const a=[...f];if(reportable(p.reporting_treatment)&&!p.approved_report_language?.trim())a.push("Reportable findings require approved report language.");if(responseRequired(i)&&!i.responseWaived&&(!p.management_response_evaluation?.trim()||!["accepted","insufficient"].includes(p.management_response_status)))a.push("Required management response must be evaluated.");if(i.operationalStatus==="resolved"&&!p.resolution_narrative?.trim())a.push("Resolved findings require a resolution narrative.");return{submissionEligible:!f.length,approvalEligible:!a.length,failures:f,approvalFailures:a}}
export type FindingGates=ReturnType<typeof deriveFindingGates>;
export function hasCurrentApproval(p:FindingProfile){return p.review_status==="approved"&&p.approved_version===p.version&&Boolean(p.reviewed_at&&p.reviewed_by_name)}
export function isReportingCandidate(p:FindingProfile,g:FindingGates){return g.approvalEligible&&reportable(p.reporting_treatment)&&Boolean(p.approved_report_language?.trim())}
export function isFinalReportableFinding(s:string,p:FindingProfile,g:FindingGates){return s==="complete"&&hasCurrentApproval(p)&&isReportingCandidate(p,g)}
export type Phase5FindingProjection={issueId:string;reference:string;title:string;narrative:string;category:string;findingType:string;severity:string;materiality:FindingMateriality;impacts:FindingImpact[];linkedAddBacks:Array<{id:string;relationship:string;amount:number;status:string}>;evidence:Array<{type:string;id:string;relationship:string;inherited:boolean}>;sourceInvestigations:Array<{id:string;relationship:string;reference:string|null}>;transactionImplication:string|null;recommendation:string|null;managementResponse:string|null;managementResponseEvaluation:string|null;resolution:string|null;reportingTreatment:ReportingTreatment;executiveSummary:boolean;includeInQoeAdjustments:boolean;transactionConsideration:boolean;approvedReportLanguage:string;reviewedBy:string|null;reviewedAt:string|null;version:number;approvedVersion:number;lastActivity:{eventType:string;actor:string;createdAt:string}|null};
